[project]
name = "pisense-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.3",
    "logging>=0.4.9.6",
    "mariadb>=1.1.14",
    "nox>=2025.11.12",
]

[dependency-groups]
tests = [
    "flake8>=7.3.0",
    "pytest>=9.0.2",
]
