services:
  mariadb:
    image: mariadb:12.2
    restart: always
    container_name: mariadb
    environment:
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
    ports:
      - ${MARIADB_PORT}:3306
    healthcheck: # https://mariadb.com/docs/server/server-management/automated-mariadb-deployment-and-administration/docker-and-mariadb/using-healthcheck-sh
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./db_data:/var/lib/mysql # Persistant storage
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Initial Script
    networks:
      - pisense-network

  pisense:
    image: pisense:latest
    container_name: pisense
    restart: always
    ports:
      - ${PISENSE_BACKEND_PORT}:8000
    networks:
      - pisense-network
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  pisense-network:
