# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Running NOX Tests

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  nox-tests:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install C dependencies
      run: sudo apt-get update && sudo apt-get install -y libmariadb3 libmariadb-dev

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      # Runs nox tests with dependency group `tests`
      run: uv run --group tests nox
  
  build-docker:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
    steps:
    - uses: actions/checkout@v4

    - name: Setup pisense env file
      uses: cuchi/jinja2-action@v1.3.0
      with:
        template: docker/env.j2
        output_file: .env
        strict: true
      env:
        MARIADB_DATABASE: ${{ env.TEST_MARIADB_DATABASE }}
        MARIADB_USER: ${{ env.TEST_MARIADB_USER }}
        MARIADB_PASSWORD: ${{ env.TEST_MARIADB_PASSWORD }}
        MARIADB_ROOT_PASSWORD: ${{ env.TEST_MARIADB_ROOT_PASSWORD }}
        MARIADB_PORT: 3306
        MARIADB_HOST: mariadb
        PISENSE_BACKEND_PORT: 8000

    - name: Check if .env exists
      run: ls -a

    - name: Build Docker image
      run: docker buildx build -f docker/Dockerfile . -t pisense:latest

  build-compose:
    runs-on: ubuntu-latest
    needs: build-docker
    env:
      FORCE_COLOR: "1"
    steps:
    - uses: actions/checkout@v4

    - name: Get remote image
      run: docker image pull mariadb:12.2

    - name: See built images
      run: docker image list

    - name: Setup compose env file
      uses: cuchi/jinja2-action@v1.3.0
      with:
        template: docker/env.j2
        output_file: docker/.env
        strict: true
      env:
        MARIADB_DATABASE: ${{ env.TEST_MARIADB_DATABASE }}
        MARIADB_USER: ${{ env.TEST_MARIADB_USER }}
        MARIADB_PASSWORD: ${{ env.TEST_MARIADB_PASSWORD }}
        MARIADB_ROOT_PASSWORD: ${{ env.TEST_MARIADB_ROOT_PASSWORD }}
        MARIADB_PORT: 3306
        MARIADB_HOST: mariadb
        PISENSE_BACKEND_PORT: 8000
      
    - name: Check if .env exists
      run: ls -a docker